baseURL = 'https://lambda-m.nl/blog/'
languageCode = 'en-us'
title = '(Lambda M)'
theme = 'LambdaM'
enableInlineShortcodes = true

[Params.Author]
  name = "Maarten"
  abstract = """
  I'm an idiot.
  """
[pagination]
  pagerSize = 10

[Params]
  twittercard = true
  # darkmode = true # set true if you want to enforce dark mode
  lightmode = true # set true if you want to enforce light mode